### ISSUE TITLE
There is no alert to inform user that Bluetooth is disabled and prompt user to open the phone settings

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#319]
Seen on Initial Setup flow. 
There is only a request to allow Bluetooth usage

This window was showing up previously
![Screenshot at May 24 15-56-45](https://user-images.githubusercontent.com/47991168/119356804-81eca380-bcaf-11eb-8d2b-4829ce58ec82.png)
Please, change the text:
Title - "Bluetooth is powered off"
Body - "You can allow new connections or turn on Bluetooth in Settings"

**Comment by NSFriend** [comment]
Since it is not possible to lead user to Bluetooth settings from our custom alert

In case when Bluetooth is turned off from settings will be shown following system alert:


![IMG_1106](https://user-images.githubusercontent.com/45981658/119384551-8aec6d80-bccd-11eb-9666-b67b41e37ea3.PNG)


In case when Bluetooth is turned off only from bottom sheet settings will be shown following system alert:

![IMG_1107](https://user-images.githubusercontent.com/45981658/119384791-e585c980-bccd-11eb-984c-24382df42130.PNG)
