### ISSUE TITLE
User don't see pair request alert when app is in foreground.

### ISSUE THREAD

**Issue by Ivan-Skoryk** [Faifly/xDrip#92]
Try to connect to unpaired transmitter. You won't see any pair request alerts if app will be in foreground.

**Comment by qwqatest** [comment]
I didn't get a pairing request while the app was in the background during Initial Setup. I've tried two times and waited for about 30 minutes. 
Logs during those attempts:

![Screenshot at Nov 16 12-37-40](https://user-images.githubusercontent.com/47991168/99250820-f59b8880-2814-11eb-9620-9517493e4051.png)
![Screenshot at Nov 16 12-52-32](https://user-images.githubusercontent.com/47991168/99250849-077d2b80-2815-11eb-8db0-361b1831fab0.png)


And took 20 minutes to get a pairing request after screen lock. When screen is on, I got a pairing request after 2 min. 39 sec.

The problem is reproducible only during Initial Setup in my case. When pairing from the app Settings pairing request worked fine
